version: '3'

vars:
  # SERVICE: none
  BUILD_DIR: build

tasks:
  prebuild:
    dir: "{{.BUILD_DIR}}/app"
    deps: [clean]
    cmds:
      - cp -a ../../template/golang-graphql/ .
      # - rm -rf ./function
      - cat ./function/gqlgen.yml >> gqlgen.yml
  
  test:
    dir: "{{.BUILD_DIR}}/app"
    deps: [prebuild]
    cmds:
      - gqlgen generate
      - cat function/GO_REPLACE.txt >> ./go.mod || exit 0
      - test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./function/vendor/*"))"
      - go test ./function/... -cover


  build:
    dir: "{{.BUILD_DIR}}/app"
    deps: [test]
    cmds:
      - go build --ldflags "-s -w" -installsuffix cgo -o ./bin/handler .
  
  clean:
    cmds:
      - rm -rf {{.BUILD_DIR}}
